name: Daily News Scraper

on:
  schedule:
    - cron: '0 6 * * *'    
    - cron: '0 12 * * *' 
    - cron: '0 18 * * *' 
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false 
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          python src/scraper.py

      - name: Commit Changes
        run: |
          git config user.name "NotSooShariff"
          git config user.email "osh.econnect@gmail.com"
          git add output/
          git commit -m "Add news headlines for $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.PAT_TOKEN }}  
            branch: main
     
